server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/medbill
spring.datasource.username=medbill
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

application.security.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970


watsonx.api.url=https://us-south.ml.cloud.ibm.com
watsonx.api.key={WATSONX_API_KEY}
watsonx.project.id={WATSONX_PROJECT_ID}
watsonx.model.id=ibm/granite-13b-instruct-v2

frontend.url=http://localhost:5173

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB